window.PAGE_COPY = {
  pageTitle: 'Frontend Birthday Protocol',
  metaDescription: 'Pixel-art frontend birthday card with hidden interactions and a secret counter.',
  cardTitle: '◉ [SYSTEM] BIRTHDAY EVENT TRIGGERED ◉',
  eggCounterLabel: 'SECRET HUNTER',
  profileTopTitle: 'DEV PROFILE',
  profileRoleLabel: 'ROLE:',
  profileRoleValue: 'LEGENDARY DEV',
  profileStackLabel: 'STACK:',
  profileStackValue: 'WP • HTML • CSS • JS',
  profileCodingSinceLabel: 'CODING SINCE:',
  profileCodingSinceValue: 'BEFORE IT WAS COOL',
  codeBadgeLabel: 'JS',
  codeTitleLabel: 'birthday.js',
  birthdayTitleHtml: 'HAPPY FUСKING<br>BIRTHDAY',
  birthdayTitleAccent: 'заебал!',
  birthdaySubtextHtml: 'Поздравляю, ты стареешь.<br>Пусть Баги боятся тебя, а не наоборот.',
  commandPanelTitle: '>_ secret-terminal',
  commandLogIntroHtml:
    '<div>&gt;_ заебал вошёл в чат. Готовьтесь, суки.</div>' +
    '<div>Нажмите <button type="button" class="command-hint-chip" data-command="help">help</button>, если нужен список разрешённых безобразий.</div>',
  footerCopyHtml:
    'MADE WITH <button class="footer-icon footer-icon-heart footer-action" type="button" data-easter="hearts" aria-label="Launch hearts"><big>♥</big></button> AND TOO MUCH CSS • 2026',
  mobileIntroEyebrow: 'FIRST RUN / MOBILE MODE',
  mobileIntroTitle: 'Мобилка пофикшена',
  mobileIntroTextHtml:
    'Да, на телефоне теперь не разваливается. Но <strong>весь челлендж лучше проходить на десктопе</strong>: тут есть клавиатурные трюки, а мобильная клавиатура всё равно делает вид, что она помогает.',
  mobileIntroClose: 'Понятно',
  secretModalEyebrow: 'ACHIEVEMENT UNLOCKED',
  secretModalTitle: 'РЕЖИМ ЛЕГЕНДЫ',
  secretModalText: 'Ты нашёл скрытый слой. Теперь сайт ведёт себя так, будто ему дали root и не забрали.',
  secretModalRestart: 'Пройти сначала',
  codeModalTitle: 'birthday.js',
  audioModalEyebrow: 'SOUND SYSTEM / WARNING',
  audioModalTitle: 'Включить звуковое безумие?',
  audioModalText:
    'Страница начнёт пищать, свистеть и щёлкать синтезаторами так, будто она сбежала из аркадного зала. Точно хотите услышать это безумие?',
  audioModalConfirm: 'Да, запускай сирены',
  audioModalCancel: 'Не сегодня, я ещё люблю тишину'
}

window.BIRTHDAY_CODE = {
  commentPlain: '// тише-тише, сейчас напечатаем',
  preludePlain: 'Lorem ipsum dolor sit amet',
  cursorGlyph: '▌',
  reactionAsideText: 'бля',
  plain: `const celebration = {\n  person: "OLEX",\n  level: 9999,\n  status: "EPIC",\n  coffee: Infinity,\n  bugs: 0,\n  message: "С Днём рождения, ЛЕГЕНДА. Багов ноль. Подозрительно, но приятно. Система стабильна, но это временно."\n};\n\nexport default celebration;`,
  finalHtml: `<span class="code-keyword">const</span> celebration = {\n  person: <span class="code-string">"OLEX"</span>,\n  level: <span class="code-number">9999</span>,\n  status: <span class="code-string">"EPIC"</span>,\n  coffee: <span class="code-number">Infinity</span>,\n  bugs: <span class="code-number">0</span>,\n  message: <span class="code-string">"С Днём рождения, ЛЕГЕНДА. Багов ноль. Подозрительно, но приятно. Система стабильна, но это временно."</span>\n};\n\n<span class="code-keyword">export</span> <span class="code-keyword">default</span> celebration<span class="code-punct">;</span>`
}

window.EGG_CATALOG = {
  portrait: 'Портрет принят. Интерфейс сделал вид, что так и задумано',
  hearts: 'Soft skills прошли ревью без единого комментария',
  trophy: 'Кубок признал владельца и перестал спорить',
  deploy: 'birthday.js ушёл в прод без совещания',
  terminal: 'Терминал открыт. Теперь страница слушает внимательно',
  share: 'Ссылка готова к выпуску в дикую сеть',
  cake: 'Торт запущен. Праздник перешёл в активную фазу',
  longPress: 'Long press обнаружен. Сайт занёс это в логи',
  party: 'Party mode. Компилятор временно снял галстук',
  matrix: 'Matrix layer. Таблица стилей смотрит первой',
  legendary: 'Legendary mode. CSS держится на характере и наглости',
  coffee: '/GOD_MODE проснулся, но попросил вести себя прилично',
  brew: 'Brew mode. Runtime попросил вторую кружку',
  bugfix: 'Bugfix complete. Баги сменили фамилию и ушли в backlog',
  frontend: 'Набрано frontend. Верстка подняла бровь',
  birthday: 'Набрано birthday. Праздник забрал root-доступ',
  combo: 'Click combo x7. Ручной QA вышел из-под контроля'
}

window.EGG_HINTS = {
  portrait: 'Портрет выглядит слишком кликабельным, чтобы ему доверять.',
  hearts: 'Сердце в футере не просто для красоты. Оно подозрительно живое.',
  trophy: 'Кубок в профиле хочет, чтобы его признали.',
  deploy: 'birthday.js не сам себя деплойнет. Хотя очень старается.',
  terminal: 'Слэш открывает не только путь, но и терминал.',
  share: 'В футере есть кнопка, которая выпускает хаос наружу.',
  cake: 'Торт в футере не просто украшение. Он тоже умеет праздновать.',
  longPress: 'Иногда страницу надо не кликать, а давить авторитетом.',
  party: 'Терминал понимает party. К сожалению для продакшена.',
  matrix: 'Терминал видел белого кролика. Попробуй matrix.',
  legendary: 'Есть режим легенды. Команда obvious, код не очень.',
  coffee: 'Кофе можно не пить, а выполнить.',
  brew: 'Если coffee мало, терминал понимает brew.',
  bugfix: 'Терминал умеет делать вид, что баги побеждены.',
  frontend: 'Некоторые слова можно набрать руками или прямо в терминале.',
  birthday: 'Одно праздничное слово работает и на клавиатуре, и в терминале.',
  combo: 'Семь быстрых кликов превращают QA в контактный спорт.'
}

window.UI_COPY = {
  themeToggleToDark: 'Switch to dark theme',
  themeToggleToLight: 'Switch to light theme',
  soundToggleEnable: 'Enable sound',
  soundToggleDisable: 'Disable sound',
  secretHunterModalTitle: 'SECRET HUNTER',
  secretHunterModalText:
    'Пасхалки спрятаны по странице. Кликайте подозрительное, жмите / для терминала, а frontend, birthday и coffee можно набрать руками или в терминале.',
  everythingFoundTitle: 'ВСЁ НАЙДЕНО',
  everythingFoundText: 'Любопытство уровня senior, терпение уровня человек без дедлайна.',
  everythingFoundProgress: 'Можно требовать премию за ручной QA и моральный ущерб.',
  resetProgressToast: 'Прогресс сброшен. Пасхалки снова прячутся как ни в чём не бывало.',
  progressSavedToast: 'Прогресс сохранён для этой сессии.',
  soundAlreadyEnabledToast: 'Sound включён. Предупреждение уже было.',
  soundDisabledToast: 'Sound выключен. Тишина снова на вахте.',
  soundEnabledToast: 'Звук включён. Теперь страница щёлкает, свистит и довольно собой.',
  silenceWonToast: 'Тишина победила. Безумие подождёт.',
  helpOpenedToast: 'Help открыт. Теперь у хаоса хотя бы есть меню.',
  darkModeBackToast: 'Тёмная тема вернулась. Прод снова выглядит уверенно.',
  lightModeVisitingToast: "Don\'t push the horses!  Светлая тема здесь временно.",
  darkModeRestoredToast: 'Тёмная тема восстановлена. Интерфейс снова в своей среде.',
  shareCopiedToast: 'Share API спит, ссылка скопирована.',
  shareSentToast: 'Share улетел. Интернет предупреждён.',
  shareCancelledToast: 'Share отменён. Драма без релиза.',
  shareFailedToast: 'Share споткнулся. Ссылка осталась жива.',
  matrixOffToast: 'Matrix layer выключен. Реальность снова делает вид, что стабильна.',
  matrixOnToast: 'Matrix layer включён. Реальность пошла зелёными строками.',
  partyOnToast: 'Party mode включён. Экран официально потерял контроль.',
  beerToast: 'Beer mode. Дедлайн ослабил галстук и сделал вид, что не видел.',
  bugfixToast: 'Bugfix mode. Плюсы вышли на зачистку.',
  heartToast: 'Heart mode. Страница внезапно вспомнила про soft skills.',
  trophyToast: 'Trophy lift-off. Кубок понял, кто тут главный.',
  deployToast: 'Deploying birthday.js... кэш держится на честном слове.',
  cakeToast: 'Cake smash. Сердца, торт и салют полетели в карточке.',
  unknownButtonToast: 'Кнопка есть, смысла пока нет. Классика.',
  commandRejectedToastTemplates: [
    'Команда "{command}" ушла в /dev/null без права апелляции.',
    'Терминал посмотрел на "{command}" и выбрал молчание.',
    '"{command}" не команда. Это попытка.'
  ],
  commandUnknownHtmlVariants: [
    'Команда <span>{command}</span> принята. Отклонена. Спасибо за участие.',
    '<span>{command}</span> не команда. Это попытка.',
    '[404] смысл команды <span>{command}</span> не найден.'
  ],
  emptyCommandHtmlVariants: [
    '$ _ Терминал слушает. Терминал начинает сомневаться.',
    '$ _ Пустая команда выполнена. Результат тоже пустой.',
    '$ _ Enter без текста принят как философская позиция.'
  ],
  terminalPrompt: '$',
  commandPanelHelpPrefix: 'Команды терминала, которые ещё не стыдно нажать: ',
  commandPartyLog: '&gt; Вечеринка активирована. Снимай штаны с продакшена',
  commandDeployLog: '&gt; Деплойнул в прод. Если упадёт — сам виноват',
  commandMatrixLog: '&gt; Следуй за белым кроликом...',
  commandLegendaryLog: '&gt; Ты и так легенда, просто пока не все в курсе',
  commandCoffeeLog: '&gt; /GOD_MODE открыт. Кофе принят без дешёвых мемов',
  commandFrontendLog: '&gt; Frontend режим поднят. Верстка сделала вид, что так и было',
  commandBirthdayLog: '&gt; Birthday режим активирован. Торт пошёл в атаку',
  commandBrewLog: 'Brew выполнен: runtime попросил вторую кружку, дедлайн сделал вид, что занят.',
  commandBugfixLog: 'Bugfix mode: плюсы на поле, баги уже пишут объяснительную.',
  commandClearLog: '&gt; Память очищена. Как твоя совесть после дедлайна',
  commandZaebalLog: '&gt; Сам заебал, но я тебя люблю',
  commandShareLog: '&gt; Share protocol armed. Ссылку можно выпускать в дикую природу',
  cakeLog: '&gt; Торт в футере запустил праздничный разнос',
  heartsLog: '&gt; Сделано с душой: too much coffee, матом и нормальным ревью',
  portraitLog: '&gt; Не тыкай в меня, я и так красавчик',
  longPressLog: '&gt; Long press обнаружен. Сайт занёс это в логи. Без комментариев.',
  heartsToast: 'Сделано с душой: too much coffee, матом и нормальным ревью.',
  portraitToast: 'Портрет потроган. Самооценка выдержала.',
  longPressDetectedToast: 'Long press detected. Да, сайт тоже осуждает.',
  commandTerminalResponseClear: 'Память очищена. Совесть тоже попробовала.',
  commandTerminalResponseParty: 'Вечеринка активирована. Снимай штаны с продакшена',
  commandTerminalResponseDeploy: [
    'Деплойнул в прод. Если упадёт — сам виноват',
    'npm run build — OK',
    'deploy complete — именинник уже в проде, откат запрещён'
  ],
  commandTerminalResponseMatrix: 'Следуй за белым кроликом...',
  commandTerminalResponseLegendary: 'Ты и так легенда, просто пока не все в курсе',
  shareFailedModalTitle: 'SHARE FAILED SUCCESSFULLY',
  shareFailedModalPrefix: 'Скопируй руками: ',
  sharePageTitle: 'Frontend Birthday Protocol',
  sharePageText: 'Зацени birthday-протокол. CSS, мат и ручной QA уже внутри.',
  beerModeModalTitle: 'BEER MODE',
  beerModeModalText: 'Brew запущен. Runtime попросил вторую кружку, дедлайн сделал вид, что занят.',
  bugfixModalTitle: 'БАГФИКС ВЫШЕЛ НА СМЕНУ',
  bugfixModalText: 'Баги не исчезли. Они просто сменили имя и спрятались в чужом backlog.',
  legendaryModalTitle: 'РЕЖИМ ЛЕГЕНДЫ',
  legendaryModalText: 'Ты нашёл скрытый слой. Теперь сайт сияет так, будто сам себе поставил senior.',
  comboModalTitle: 'CLICK COMBO x7',
  comboModalText: 'Семь кликов подряд. Это уже не тестирование, это ручной стресс-тест без бюджета.',
  eggHintPrefix: 'Подсказка: ',
  eggFoundPrefix: 'Пасхалка найдена: ',
  coffeeModeTitle: 'COFFEE РЕЖИМ',
  coffeeModeText: 'Ты набрал coffee. /GOD_MODE проснулся и попросил не злоупотреблять властью.',
  frontendModeTitle: 'FRONTEND РЕЖИМ',
  frontendModeText: 'Ты набрал frontend. Скобки полезли на экран: интерфейс решил доказать, что у него есть архитектура.',
  birthdayModeTitle: 'BIRTHDAY РЕЖИМ',
  birthdayModeText: 'Ты набрал birthday. Торт пошёл в атаку, потому что обычное поздравление было бы слишком скучным.',
  coffeeModeTextAlt: 'Ты набрал coffee. Клавиатура моргнула и открыла /GOD_MODE.',
  brewSpillToast: 'Brew mode. Runtime запросил вторую кружку.',
  coffeeSpillToast: 'Coffee mode. Интерфейс проснулся и уже спорит с продом.',
  deploySteps: [
    'npm run build — OK',
    'lint skipped — birthday emergency protocol без лишних вопросов',
    'deploy complete — именинник уже в проде, откат запрещён'
  ]
}
