window.APP_COPY = {
  en: {
    PAGE_COPY: {
      pageTitle: 'Frontend Birthday Protocol',
      metaDescription: 'Pixel-art birthday card with hidden interactions, terminal tricks, and a secret counter.',
      cardTitle: '◉ [SYSTEM] BIRTHDAY EVENT TRIGGERED ◉',
      eggCounterLabel: 'SECRET HUNTER',
      profileTopTitle: 'DEV PROFILE',
      profileRoleLabel: 'ROLE:',
      profileRoleValue: 'LEGENDARY DEV',
      profileStackLabel: 'STACK:',
      profileStackValue: 'WP • HTML • CSS • JS',
      profileCodingSinceLabel: 'CODING SINCE:',
      profileCodingSinceValue: 'BEFORE IT WAS COOL',
      codeBadgeLabel: 'JS',
      codeTitleLabel: 'birthday.js',
      birthdayTitleHtml: 'HAPPY FUCKING<br>BIRTHDAY',
      birthdayTitleAccent: 'you glorious bastard!',
      birthdaySubtextHtml: 'Happy birthday. May the bugs fear you, not the other way around.',
      commandPanelTitle: '>_ secret-terminal',
      commandLogIntroHtml:
        '<div>&gt;_ you just opened the chat. Brace yourself.</div>' +
        '<div>Hit <button type="button" class="command-hint-chip" data-command="help">help</button> for the list of approved nonsense.</div>',
      footerCopyHtml:
        'MADE WITH <button class="footer-icon footer-icon-heart footer-action" type="button" data-easter="hearts" aria-label="Launch hearts"><big>♥</big></button> AND WAY TOO MUCH CSS • 2026',
      mobileIntroEyebrow: 'FIRST RUN / MOBILE MODE',
      mobileIntroTitle: 'Mobile patched',
      mobileIntroTextHtml:
        'Yes, it no longer falls apart on phones. But <strong>the full challenge still plays best on desktop</strong>: that is where the keyboard tricks live, and mobile keyboards still act like they are helping.',
      mobileIntroClose: 'Got it',
      secretModalEyebrow: 'ACHIEVEMENT UNLOCKED',
      secretModalTitle: 'LEGEND MODE',
      secretModalText: 'You found the hidden layer. Now the site behaves like it just got root and decided to keep it.',
      secretModalRestart: 'Restart from scratch',
      codeModalTitle: 'birthday.js',
      audioModalEyebrow: 'SOUND SYSTEM / WARNING',
      audioModalTitle: 'Turn on the sound chaos?',
      audioModalText:
        'The page will beep, hiss, and click its synths like it escaped an arcade cabinet. Are you sure you want to hear this mess?',
      audioModalConfirm: 'Yes, fire the sirens',
      audioModalCancel: 'Not today, I still like silence'
    },
    BIRTHDAY_CODE: {
      commentPlain: '// quiet now, we are typing',
      preludePlain: 'Lorem ipsum dolor sit amet',
      cursorGlyph: '▌',
      reactionAsideText: 'damn',
      plain: `const celebration = {\n  person: "OLEX",\n  level: 9999,\n  status: "EPIC",\n  coffee: Infinity,\n  bugs: 0,\n  message: "Happy birthday, legend. Zero bugs. Suspicious, but nice. The system is stable, but only for now."\n};\n\nexport default celebration;`,
      finalHtml: `<span class="code-keyword">const</span> celebration = {\n  person: <span class="code-string">"OLEX"</span>,\n  level: <span class="code-number">9999</span>,\n  status: <span class="code-string">"EPIC"</span>,\n  coffee: <span class="code-number">Infinity</span>,\n  bugs: <span class="code-number">0</span>,\n  message: <span class="code-string">"Happy birthday, legend. Zero bugs. Suspicious, but nice. The system is stable, but only for now."</span>\n};\n\n<span class="code-keyword">export</span> <span class="code-keyword">default</span> celebration<span class="code-punct">;</span>`
    },
    EGG_CATALOG: {
      portrait: 'Portrait accepted. The interface acted like it was intentional.',
      hearts: 'Soft skills passed review without a single comment.',
      trophy: 'The trophy acknowledged its rightful owner and stopped arguing.',
      deploy: 'birthday.js got deployed to prod without a meeting.',
      terminal: 'Terminal opened. The page is listening closely now.',
      share: 'Link is ready to be released into the wild.',
      cake: 'Cake launched. The party is now in active duty.',
      longPress: 'Long press detected. The site logged it for future evidence.',
      party: 'Party mode. The compiler loosened its tie.',
      matrix: 'Matrix layer. The stylesheet took the wheel.',
      legendary: 'Legendary mode. CSS is running on attitude and spite.',
      coffee: '/GOD_MODE woke up and asked for a little restraint.',
      brew: 'Brew mode. Runtime asked for a second cup.',
      bugfix: 'Bugfix complete. The bugs changed names and entered the backlog.',
      frontend: 'Typed frontend. The layout raised an eyebrow.',
      birthday: 'Typed birthday. The cake claimed root access.',
      combo: 'Click combo x7. Manual QA has become a contact sport.'
    },
    EGG_HINTS: {
      portrait: 'The portrait looks suspiciously clickable.',
      hearts: 'The heart in the footer is not just decorative. It is acting weird.',
      trophy: 'The trophy in the profile wants recognition.',
      deploy: 'birthday.js will not deploy itself. It is trying, though.',
      terminal: 'The slash opens more than a path. It opens the terminal too.',
      share: 'There is a button in the footer ready to release chaos.',
      cake: 'The footer cake is not only decoration. It knows how to celebrate.',
      longPress: 'Sometimes the page does not want a click. It wants pressure.',
      party: 'The terminal understands party. Unfortunately for production.',
      matrix: 'The terminal has seen the white rabbit. Try matrix.',
      legendary: 'There is a legendary mode. The command is obvious, the code is not.',
      coffee: 'Coffee does not have to be drunk. It can be executed.',
      brew: 'If coffee is not enough, the terminal understands brew.',
      bugfix: 'The terminal can also pretend the bugs have been beaten.',
      frontend: 'Some words can be typed by hand or directly in the terminal.',
      birthday: 'One festive word works both on the keyboard and in the terminal.',
      combo: 'Seven fast clicks turn QA into a contact sport.'
    },
    UI_COPY: {
      themeToggleToDark: 'Switch to dark theme',
      themeToggleToLight: 'Switch to light theme',
      themeToggleLabelDark: 'Dark',
      themeToggleLabelLight: 'Light',
      soundToggleEnable: 'Enable sound',
      soundToggleDisable: 'Disable sound',
      soundToggleLabelOn: 'On',
      soundToggleLabelOff: 'Off',
      languageToggleToRussian: 'Switch to Russian',
      languageToggleToEnglish: 'Switch to English',
      languageToggleLabelEnglish: 'EN',
      languageToggleLabelRussian: 'RU',
      secretHunterModalTitle: 'SECRET HUNTER',
      secretHunterModalText:
        'Easter eggs are hiding all over the page. Click suspicious things, press / for the terminal, and type frontend, birthday, or coffee either here or in the terminal.',
      everythingFoundTitle: 'EVERYTHING FOUND',
      everythingFoundText: 'Senior-level curiosity, zero-deadline patience.',
      everythingFoundProgress: 'You may now invoice for manual QA and emotional damage.',
      resetProgressToast: 'Progress reset. The eggs are hiding again like nothing happened.',
      progressSavedToast: 'Progress saved for this session.',
      soundAlreadyEnabledToast: 'Sound is already on. The warning already happened.',
      soundDisabledToast: 'Sound off. Silence is back on duty.',
      soundEnabledToast: 'Sound on. The page now clicks, hisses, and thinks it is brilliant.',
      silenceWonToast: 'Silence won. The chaos will wait.',
      helpOpenedToast: 'Help opened. Chaos now at least has a menu.',
      darkModeBackToast: 'Dark mode is back. Prod looks confident again.',
      lightModeVisitingToast: "Don't push the horses! Light mode is only visiting.",
      darkModeRestoredToast: 'Dark mode restored. The interface is back home.',
      shareCopiedToast: 'Share API is asleep. Link copied.',
      shareSentToast: 'Share sent. The internet has been warned.',
      shareCancelledToast: 'Share canceled. Drama, no release.',
      shareFailedToast: 'Share tripped. The link survived.',
      matrixOffToast: 'Matrix layer off. Reality is pretending to be stable again.',
      matrixOnToast: 'Matrix layer on. Reality went full green stream.',
      partyOnToast: 'Party mode on. The screen has officially lost control.',
      beerToast: 'Beer mode. The deadline loosened its tie and looked away.',
      bugfixToast: 'Bugfix mode. The pluses are on cleanup duty.',
      heartToast: 'Heart mode. The page suddenly remembered soft skills.',
      trophyToast: 'Trophy lift-off. The cup knows who is in charge.',
      deployToast: 'Deploying birthday.js... cache is held together by optimism.',
      cakeToast: 'Cake smash. Hearts, cake, and sparks are flying.',
      unknownButtonToast: 'Button exists. Meaning pending. Classic.',
      commandRejectedToastTemplates: [
        'Command "{command}" went to /dev/null without parole.',
        'Terminal looked at "{command}" and chose silence.',
        '"{command}" is not a command. It is a plea.'
      ],
      commandUnknownHtmlVariants: [
        'Command <span>{command}</span> accepted. Rejected. Thank you for your service.',
        '<span>{command}</span> is not a command. It is a plea.',
        '[404] meaning for <span>{command}</span> not found.'
      ],
      emptyCommandHtmlVariants: [
        '$ _ Terminal listening. Terminal is now reconsidering its life choices.',
        '$ _ Empty command executed. The result is also empty.',
        '$ _ Enter with no text logged as a philosophical statement.'
      ],
      terminalPrompt: '$',
      commandPanelHelpPrefix: 'Terminal commands that still have some dignity left: ',
      commandPartyLog: '&gt; Party activated. Pants off the production server',
      commandDeployLog: '&gt; Deployed to prod. If it breaks, it was not me',
      commandMatrixLog: '&gt; Follow the white rabbit...',
      commandLegendaryLog: '&gt; You are already legendary, some people just do not know it yet',
      commandCoffeeLog: '&gt; /GOD_MODE opened. Coffee accepted without the cheap meme',
      commandFrontendLog: '&gt; Frontend mode up. The layout pretended this was always the plan',
      commandBirthdayLog: '&gt; Birthday mode activated. The cake went on the offensive',
      commandBrewLog: 'Brew executed: runtime asked for a second cup, deadline acted busy.',
      commandBugfixLog: 'Bugfix mode: the pluses are on the field, the bugs are already writing an apology.',
      commandClearLog: '&gt; Memory cleared. Same as after a deadline',
      commandZaebalLog: '&gt; You are a menace, but I still like you',
      commandShareLog: '&gt; Share protocol armed. Release the link into the wild',
      cakeLog: '&gt; The footer cake launched the birthday takeover',
      heartsLog: '&gt; Made with heart: too much coffee, a little profanity, and a proper review',
      portraitLog: '&gt; Do not poke me, I am already handsome',
      longPressLog: '&gt; Long press detected. The site logged it. No further comments.',
      heartsToast: 'Made with heart: too much coffee, a little profanity, and a proper review.',
      portraitToast: 'Portrait touched. Ego survived.',
      longPressDetectedToast: 'Long press detected. Yes, the site is judging you too.',
      commandTerminalResponseClear: 'Memory cleared. So did your conscience.',
      commandTerminalResponseParty: 'Party activated. Pants off the production server',
      commandTerminalResponseDeploy: [
        'Deployed to prod. If it breaks, it was not me',
        'npm run build — OK',
        'deploy complete — the birthday guest is already in prod, rollback forbidden'
      ],
      commandTerminalResponseMatrix: 'Follow the white rabbit...',
      commandTerminalResponseLegendary: 'You are already legendary, some people just do not know it yet',
      shareFailedModalTitle: 'SHARE FAILED SUCCESSFULLY',
      shareFailedModalPrefix: 'Copy this manually: ',
      sharePageTitle: 'Frontend Birthday Protocol',
      sharePageText: 'Check out the birthday protocol. CSS, chaos, and manual QA included.',
      beerModeModalTitle: 'BEER MODE',
      beerModeModalText: 'Brew is live. Runtime asked for a second pint, and the deadline looked away.',
      bugfixModalTitle: 'BUGFIX ON DUTY',
      bugfixModalText: 'The bugs did not disappear. They just changed names and hid in someone else\'s backlog.',
      legendaryModalTitle: 'LEGEND MODE',
      legendaryModalText: 'You found the hidden layer. Now the site shines like it promoted itself to senior.',
      comboModalTitle: 'CLICK COMBO x7',
      comboModalText: 'Seven clicks in a row. That is no longer testing, that is manual stress testing on a broken budget.',
      eggHintPrefix: 'Hint: ',
      eggFoundPrefix: 'Easter egg found: ',
      coffeeModeTitle: 'COFFEE MODE',
      coffeeModeText: 'You typed coffee. /GOD_MODE woke up and asked for a little restraint.',
      frontendModeTitle: 'FRONTEND MODE',
      frontendModeText: 'You typed frontend. The brackets spilled across the screen: the interface decided to prove it has architecture.',
      birthdayModeTitle: 'BIRTHDAY MODE',
      birthdayModeText: 'You typed birthday. The cake went on the offensive because a normal greeting would have been too boring.',
      coffeeModeEggToast: '/GOD_MODE is open. The keyboard blinked and pretended that was normal.',
      brewSpillToast: 'Brew mode. Runtime asked for a second cup.',
      coffeeSpillToast: 'Coffee mode. The interface woke up and is already arguing with prod.',
      deploySteps: [
        'npm run build — OK',
        'lint skipped — birthday emergency protocol, no questions asked',
        'deploy complete — the birthday guest is already in prod, rollback forbidden'
      ]
    }
  },
  ru: {
    PAGE_COPY: {
      pageTitle: 'Frontend Birthday Protocol',
      metaDescription: 'Пиксельная birthday-карточка со скрытыми взаимодействиями и секретным счётчиком.',
      cardTitle: '◉ [SYSTEM] BIRTHDAY EVENT TRIGGERED ◉',
      eggCounterLabel: 'SECRET HUNTER',
      profileTopTitle: 'DEV PROFILE',
      profileRoleLabel: 'ROLE:',
      profileRoleValue: 'LEGENDARY DEV',
      profileStackLabel: 'STACK:',
      profileStackValue: 'WP • HTML • CSS • JS',
      profileCodingSinceLabel: 'CODING SINCE:',
      profileCodingSinceValue: 'BEFORE IT WAS COOL',
      codeBadgeLabel: 'JS',
      codeTitleLabel: 'birthday.js',
      birthdayTitleHtml: 'HAPPY FUCKING<br>BIRTHDAY',
      birthdayTitleAccent: 'заебал!',
      birthdaySubtextHtml: 'Поздравляю, ты стареешь.<br>Пусть баги боятся тебя, а не наоборот.',
      commandPanelTitle: '>_ secret-terminal',
      commandLogIntroHtml:
        '<div>&gt;_ заебал вошёл в чат. Готовьтесь, суки.</div>' +
        '<div>Нажмите <button type="button" class="command-hint-chip" data-command="help">help</button>, если нужен список разрешённых безобразий.</div>',
      footerCopyHtml:
        'MADE WITH <button class="footer-icon footer-icon-heart footer-action" type="button" data-easter="hearts" aria-label="Launch hearts"><big>♥</big></button> AND TOO MUCH CSS • 2026',
      mobileIntroEyebrow: 'FIRST RUN / MOBILE MODE',
      mobileIntroTitle: 'Мобилка пофикшена',
      mobileIntroTextHtml:
        'Да, на телефоне теперь не разваливается. Но <strong>весь челлендж лучше проходить на десктопе</strong>: тут есть клавиатурные трюки, а мобильная клавиатура всё равно делает вид, что она помогает.',
      mobileIntroClose: 'Понятно',
      secretModalEyebrow: 'ACHIEVEMENT UNLOCKED',
      secretModalTitle: 'РЕЖИМ ЛЕГЕНДЫ',
      secretModalText: 'Ты нашёл скрытый слой. Теперь сайт ведёт себя так, будто ему дали root и не забрали.',
      secretModalRestart: 'Пройти сначала',
      codeModalTitle: 'birthday.js',
      audioModalEyebrow: 'SOUND SYSTEM / WARNING',
      audioModalTitle: 'Включить звуковое безумие?',
      audioModalText:
        'Страница начнёт пищать, свистеть и щёлкать синтезаторами так, будто она сбежала из аркадного зала. Точно хотите услышать это безумие?',
      audioModalConfirm: 'Да, запускай сирены',
      audioModalCancel: 'Не сегодня, я ещё люблю тишину'
    },
    BIRTHDAY_CODE: {
      commentPlain: '// тише-тише, сейчас напечатаем',
      preludePlain: 'Lorem ipsum dolor sit amet',
      cursorGlyph: '▌',
      reactionAsideText: 'бля',
      plain: `const celebration = {\n  person: "OLEX",\n  level: 9999,\n  status: "EPIC",\n  coffee: Infinity,\n  bugs: 0,\n  message: "С Днём рождения, ЛЕГЕНДА. Багов ноль. Подозрительно, но приятно. Система стабильна, но это временно."\n};\n\nexport default celebration;`,
      finalHtml: `<span class="code-keyword">const</span> celebration = {\n  person: <span class="code-string">"OLEX"</span>,\n  level: <span class="code-number">9999</span>,\n  status: <span class="code-string">"EPIC"</span>,\n  coffee: <span class="code-number">Infinity</span>,\n  bugs: <span class="code-number">0</span>,\n  message: <span class="code-string">"С Днём рождения, ЛЕГЕНДА. Багов ноль. Подозрительно, но приятно. Система стабильна, но это временно."</span>\n};\n\n<span class="code-keyword">export</span> <span class="code-keyword">default</span> celebration<span class="code-punct">;</span>`
    },
    EGG_CATALOG: {
      portrait: 'Портрет принят. Интерфейс сделал вид, что так и задумано',
      hearts: 'Soft skills прошли ревью без единого комментария',
      trophy: 'Кубок признал владельца и перестал спорить',
      deploy: 'birthday.js ушёл в прод без совещания',
      terminal: 'Терминал открыт. Теперь страница слушает внимательно',
      share: 'Ссылка готова к выпуску в дикую сеть',
      cake: 'Торт запущен. Праздник перешёл в активную фазу',
      longPress: 'Long press обнаружен. Сайт занёс это в логи',
      party: 'Party mode. Компилятор временно снял галстук',
      matrix: 'Matrix layer. Таблица стилей смотрит первой',
      legendary: 'Legendary mode. CSS держится на характере и наглости',
      coffee: '/GOD_MODE проснулся, но попросил вести себя прилично',
      brew: 'Brew mode. Runtime попросил вторую кружку',
      bugfix: 'Bugfix complete. Баги сменили фамилию и ушли в backlog',
      frontend: 'Набрано frontend. Верстка подняла бровь',
      birthday: 'Набрано birthday. Праздник забрал root-доступ',
      combo: 'Click combo x7. Ручной QA вышел из-под контроля'
    },
    EGG_HINTS: {
      portrait: 'Портрет выглядит слишком кликабельным, чтобы ему доверять.',
      hearts: 'Сердце в футере не просто для красоты. Оно подозрительно живое.',
      trophy: 'Кубок в профиле хочет, чтобы его признали.',
      deploy: 'birthday.js не сам себя деплойнет. Хотя очень старается.',
      terminal: 'Слэш открывает не только путь, но и терминал.',
      share: 'В футере есть кнопка, которая выпускает хаос наружу.',
      cake: 'Торт в футере не просто украшение. Он тоже умеет праздновать.',
      longPress: 'Иногда страницу надо не кликать, а давить авторитетом.',
      party: 'Терминал понимает party. К сожалению для продакшена.',
      matrix: 'Терминал видел белого кролика. Попробуй matrix.',
      legendary: 'Есть режим легенды. Команда obvious, код не очень.',
      coffee: 'Кофе можно не пить, а выполнить.',
      brew: 'Если coffee мало, терминал понимает brew.',
      bugfix: 'Терминал умеет делать вид, что баги побеждены.',
      frontend: 'Некоторые слова можно набрать руками или прямо в терминале.',
      birthday: 'Одно праздничное слово работает и на клавиатуре, и в терминале.',
      combo: 'Семь быстрых кликов превращают QA в контактный спорт.'
    },
    UI_COPY: {
      themeToggleToDark: 'Переключить на тёмную тему',
      themeToggleToLight: 'Переключить на светлую тему',
      themeToggleLabelDark: 'Тёмная',
      themeToggleLabelLight: 'Светлая',
      soundToggleEnable: 'Включить звук',
      soundToggleDisable: 'Выключить звук',
      soundToggleLabelOn: 'Вкл',
      soundToggleLabelOff: 'Выкл',
      languageToggleToRussian: 'Переключить на русский',
      languageToggleToEnglish: 'Переключить на английский',
      languageToggleLabelEnglish: 'EN',
      languageToggleLabelRussian: 'RU',
      secretHunterModalTitle: 'SECRET HUNTER',
      secretHunterModalText:
        'Пасхалки спрятаны по странице. Кликайте подозрительное, жмите / для терминала, а frontend, birthday и coffee можно набрать руками или в терминале.',
      everythingFoundTitle: 'ВСЁ НАЙДЕНО',
      everythingFoundText: 'Любопытство уровня senior, терпение уровня человек без дедлайна.',
      everythingFoundProgress: 'Можно требовать премию за ручной QA и моральный ущерб.',
      resetProgressToast: 'Прогресс сброшен. Пасхалки снова прячутся как ни в чём не бывало.',
      progressSavedToast: 'Прогресс сохранён для этой сессии.',
      soundAlreadyEnabledToast: 'Sound включён. Предупреждение уже было.',
      soundDisabledToast: 'Sound выключен. Тишина снова на вахте.',
      soundEnabledToast: 'Звук включён. Теперь страница щёлкает, свистит и довольно собой.',
      silenceWonToast: 'Тишина победила. Безумие подождёт.',
      helpOpenedToast: 'Help открыт. Теперь у хаоса хотя бы есть меню.',
      darkModeBackToast: 'Тёмная тема вернулась. Прод снова выглядит уверенно.',
      lightModeVisitingToast: "Don't push the horses!  Светлая тема здесь временно.",
      darkModeRestoredToast: 'Тёмная тема восстановлена. Интерфейс снова в своей среде.',
      shareCopiedToast: 'Share API спит, ссылка скопирована.',
      shareSentToast: 'Share улетел. Интернет предупреждён.',
      shareCancelledToast: 'Share отменён. Драма без релиза.',
      shareFailedToast: 'Share споткнулся. Ссылка осталась жива.',
      matrixOffToast: 'Matrix layer выключен. Реальность снова делает вид, что стабильна.',
      matrixOnToast: 'Matrix layer включён. Реальность пошла зелёными строками.',
      partyOnToast: 'Party mode включён. Экран официально потерял контроль.',
      beerToast: 'Beer mode. Дедлайн ослабил галстук и сделал вид, что не видел.',
      bugfixToast: 'Bugfix mode. Плюсы вышли на зачистку.',
      heartToast: 'Heart mode. Страница внезапно вспомнила про soft skills.',
      trophyToast: 'Trophy lift-off. Кубок понял, кто тут главный.',
      deployToast: 'Deploying birthday.js... кэш держится на честном слове.',
      cakeToast: 'Cake smash. Сердца, торт и салют полетели в карточке.',
      unknownButtonToast: 'Кнопка есть, смысла пока нет. Классика.',
      commandRejectedToastTemplates: [
        'Команда "{command}" ушла в /dev/null без права апелляции.',
        'Терминал посмотрел на "{command}" и выбрал молчание.',
        '"{command}" не команда. Это попытка.'
      ],
      commandUnknownHtmlVariants: [
        'Команда <span>{command}</span> принята. Отклонена. Спасибо за участие.',
        '<span>{command}</span> не команда. Это попытка.',
        '[404] смысл команды <span>{command}</span> не найден.'
      ],
      emptyCommandHtmlVariants: [
        '$ _ Терминал слушает. Терминал начинает сомневаться.',
        '$ _ Пустая команда выполнена. Результат тоже пустой.',
        '$ _ Enter без текста принят как философская позиция.'
      ],
      terminalPrompt: '$',
      commandPanelHelpPrefix: 'Команды терминала, которые ещё не стыдно нажать: ',
      commandPartyLog: '&gt; Вечеринка активирована. Снимай штаны с продакшена',
      commandDeployLog: '&gt; Деплойнул в прод. Если упадёт — сам виноват',
      commandMatrixLog: '&gt; Следуй за белым кроликом...',
      commandLegendaryLog: '&gt; Ты и так легенда, просто пока не все в курсе',
      commandCoffeeLog: '&gt; /GOD_MODE открыт. Кофе принят без дешёвых мемов',
      commandFrontendLog: '&gt; Frontend режим поднят. Верстка сделала вид, что так и было',
      commandBirthdayLog: '&gt; Birthday режим активирован. Торт пошёл в атаку',
      commandBrewLog: 'Brew выполнен: runtime попросил вторую кружку, дедлайн сделал вид, что занят.',
      commandBugfixLog: 'Bugfix mode: плюсы на поле, баги уже пишут объяснительную.',
      commandClearLog: '&gt; Память очищена. Как твоя совесть после дедлайна',
      commandZaebalLog: '&gt; Сам заебал, но я тебя люблю',
      commandShareLog: '&gt; Share protocol armed. Ссылку можно выпускать в дикую природу',
      cakeLog: '&gt; Торт в футере запустил праздничный разнос',
      heartsLog: '&gt; Сделано с душой: too much coffee, матом и нормальным ревью',
      portraitLog: '&gt; Не тыкай в меня, я и так красавчик',
      longPressLog: '&gt; Long press обнаружен. Сайт занёс это в логи. Без комментариев.',
      heartsToast: 'Сделано с душой: too much coffee, матом и нормальным ревью.',
      portraitToast: 'Портрет потроган. Самооценка выдержала.',
      longPressDetectedToast: 'Long press detected. Да, сайт тоже осуждает.',
      commandTerminalResponseClear: 'Память очищена. Совесть тоже попробовала.',
      commandTerminalResponseParty: 'Вечеринка активирована. Снимай штаны с продакшена',
      commandTerminalResponseDeploy: [
        'Деплойнул в прод. Если упадёт — сам виноват',
        'npm run build — OK',
        'deploy complete — именинник уже в проде, откат запрещён'
      ],
      commandTerminalResponseMatrix: 'Следуй за белым кроликом...',
      commandTerminalResponseLegendary: 'Ты и так легенда, просто пока не все в курсе',
      shareFailedModalTitle: 'SHARE FAILED SUCCESSFULLY',
      shareFailedModalPrefix: 'Скопируй руками: ',
      sharePageTitle: 'Frontend Birthday Protocol',
      sharePageText: 'Зацени birthday-протокол. CSS, мат и ручной QA уже внутри.',
      beerModeModalTitle: 'BEER MODE',
      beerModeModalText: 'Brew запущен. Runtime попросил вторую кружку, дедлайн сделал вид, что занят.',
      bugfixModalTitle: 'БАГФИКС ВЫШЕЛ НА СМЕНУ',
      bugfixModalText: 'Баги не исчезли. Они просто сменили имя и спрятались в чужом backlog.',
      legendaryModalTitle: 'РЕЖИМ ЛЕГЕНДЫ',
      legendaryModalText: 'Ты нашёл скрытый слой. Теперь сайт сияет так, будто сам себе поставил senior.',
      comboModalTitle: 'CLICK COMBO x7',
      comboModalText: 'Семь кликов подряд. Это уже не тестирование, это ручной стресс-тест без бюджета.',
      eggHintPrefix: 'Подсказка: ',
      eggFoundPrefix: 'Пасхалка найдена: ',
      coffeeModeTitle: 'COFFEE РЕЖИМ',
      coffeeModeText: 'Ты набрал coffee. /GOD_MODE проснулся и попросил не злоупотреблять властью.',
      frontendModeTitle: 'FRONTEND РЕЖИМ',
      frontendModeText: 'Ты набрал frontend. Скобки полезли на экран: интерфейс решил доказать, что у него есть архитектура.',
      birthdayModeTitle: 'BIRTHDAY РЕЖИМ',
      birthdayModeText: 'Ты набрал birthday. Торт пошёл в атаку, потому что обычное поздравление было бы слишком скучным.',
      coffeeModeEggToast: '/GOD_MODE открыт. Клавиатура моргнула и сделала вид, что так и надо.',
      brewSpillToast: 'Brew mode. Runtime запросил вторую кружку.',
      coffeeSpillToast: 'Coffee mode. Интерфейс проснулся и уже спорит с продом.',
      deploySteps: [
        'npm run build — OK',
        'lint skipped — birthday emergency protocol без лишних вопросов',
        'deploy complete — именинник уже в проде, откат запрещён'
      ]
    }
  }
};
